name: Linux Self Hosted Build Test

on: [push, pull_request]

jobs:
        
  Linux-Subsystem-Manager-Raw:
    runs-on: [self-hosted]
    strategy:
      max-parallel: 5

    steps:
    - name: Download Files
      run: |
        curl -O https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/model_installer/subsystem_manager.py
        curl -O https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/model_installer/carly_help.py
        curl -O https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/model_installer/setup_docker.py
        curl -O https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/model_installer/setup_models.py
        curl -O https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/model_installer/edit_models.py
        curl -O https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/model_installer/requirements.txt
        curl -O https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/midori_program_ver.txt
        curl -O https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/python_ver.py
        mv subsystem_manager.py model_installer.py
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Edit Subsystem Manager VER
      run: |
        python python_ver.py
        rm -f python_ver.py
    - name: Make EXE file
      run: |
        pyinstaller --onefile --clean model_installer.py
  Linux-Subsystem-Manager-Baked:
    runs-on: [self-hosted]
    strategy:
      max-parallel: 5

    steps:
    - name: Download Files
      run: |
        curl -k --disable --disable-eprt -s https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/midori_ai_manager/subsystem_python_env_setup.py > subsystem_setup.py
    - name: Make EXE file
      run: |
        python subsystem_setup.py