name: Upload Programs to Server

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  push_deb11_to_hub:
    name: Push Debian 11 to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/linux_model_deb_11

      - name: Build and push Debian 11 Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./other_files/subsystem_docker_stuff/
          file: ./other_files/subsystem_docker_stuff/midori-ai-pip-deb11-dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Clean up Docker Cache
        run: |
          docker image prune -f

  Build-Subsystem-Programs:
    name: Update Subsystem Programs
    runs-on: ubuntu-latest
    needs: push_deb11_to_hub
    steps:
      - uses: actions/checkout@v4
      - name: Update Version Name
        run: |
          mkdir -p /tmp/artifacts

      - name: Move everything to working dir
        run: |
          curl -k --disable --disable-eprt -s https://tea-cup.midori-ai.xyz/download/helper_app.py > helper_app.py
          curl -k --disable --disable-eprt -s https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/model_installer/yaml_edit.py > yaml_edit.py
          curl -k --disable --disable-eprt -s https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/midori_ai_manager/huggingface_downloader.py > huggingface_downloader.py
      
      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install -r ./other_files/model_installer/requirements.txt
          
      - name: Download the Uploader
        run: |
          python3 helper_app.py git_uploader.py
      
      - name: Build Programs
        run: |
          pyinstaller --onefile --clean --distpath /tmp/artifacts/ helper_app.py
          pyinstaller --onefile --clean --distpath /tmp/artifacts/ yaml_edit.py
          pyinstaller --onefile --clean --distpath /tmp/artifacts/ huggingface_downloader.py
      
      - name: Move Exec
        run: |
          mv /tmp/artifacts/helper_app midori_ai_downloader
          mv /tmp/artifacts/yaml_edit yaml_edit
          mv /tmp/artifacts/huggingface_downloader hf-downloader
      
      - name: Upload Raw Python
        run: |
          python3 git_uploader.py --type Linux --key ${{ secrets.UPLOADER_APIKEY }} --file "helper_app.py" --filename "helper_app.py"
          python3 git_uploader.py --type Linux --key ${{ secrets.UPLOADER_APIKEY }} --file "yaml_edit.py" --filename "yaml_edit.py"
          python3 git_uploader.py --type Linux --key ${{ secrets.UPLOADER_APIKEY }} --file "huggingface_downloader.py" --filename "huggingface_downloader.py"
      
      - name: Upload Programs
        run: |
          python3 git_uploader.py --type Linux --key ${{ secrets.UPLOADER_APIKEY }} --file "midori_ai_downloader" --filename "midori_ai_downloader"
          python3 git_uploader.py --type Linux --key ${{ secrets.UPLOADER_APIKEY }} --file "yaml_edit" --filename "yaml_edit"
          python3 git_uploader.py --type Linux --key ${{ secrets.UPLOADER_APIKEY }} --file "hf-downloader" --filename "hf-downloader"
