name: Update PixelArch and Cluster OS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:

  push_arch_to_hub:
    name: Push Midori AI's PixelArch (Arch Linux) to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/pixelarch
          tags: |
            type=raw,value=latest
            type=raw,value=quartz

      - name: Build and push Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Cluster-OS/aiclusteros/
          file: ./Cluster-OS/aiclusteros/arch_dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Clean up Docker Cache
        run: |
          docker image prune -f

  push_cluster_os_arch_to_hub:
    name: Push Cluster OS (Arch Linux) to Docker Hub
    runs-on: ubuntu-latest
    needs: push_arch_to_hub
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/midori_ai_cluster
          tags: |
            type=raw,value=latest

      - name: Build and push Cluster OS (Arch Linux) Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Cluster-OS/aiclusteros/
          file: ./Cluster-OS/aiclusteros/dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Clean up Docker Cache
        run: |
          docker image prune -f

  push_pixelarch_ver_amethyst_to_hub:
    name: Push Midori AI's PixelArch (Amethyst) to Docker Hub
    runs-on: ubuntu-latest
    needs: push_arch_to_hub
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/pixelarch
          tags: |
            type=raw,value=amethyst

      - name: Build and push Cluster OS (Amethyst) Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Cluster-OS/aiclusteros/
          file: ./Cluster-OS/aiclusteros/arch_dockerfile_amethyst
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_pixelarch_ver_topaz_to_hub:
    name: Push Midori AI's PixelArch (Topaz) to Docker Hub
    runs-on: ubuntu-latest
    needs: push_pixelarch_ver_amethyst_to_hub
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/pixelarch
          tags: |
            type=raw,value=topaz

      - name: Build and push Cluster OS (Topaz) Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Cluster-OS/aiclusteros/
          file: ./Cluster-OS/aiclusteros/arch_dockerfile_topaz
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_pixelarch_ver_emerald_to_hub:
    name: Push Midori AI's PixelArch (Emerald) to Docker Hub
    runs-on: ubuntu-latest
    needs: push_pixelarch_ver_topaz_to_hub
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/pixelarch
          tags: |
            type=raw,value=emerald

      - name: Build and push Cluster OS (Emerald) Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Cluster-OS/aiclusteros/
          file: ./Cluster-OS/aiclusteros/arch_dockerfile_emerald
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  Build-PixelArch-Programs:
    name: Update PixelArch Programs
    runs-on: ubuntu-latest
    needs: push_pixelarch_ver_emerald_to_hub
    container:
      image: lunamidori5/pixelarch:emerald

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update OS
        run: |
          yay -Syu --noconfirm

      - name: Update Version Name
        run: |
          mkdir -p /tmp/artifacts

      - name: Move everything to working dir
        run: |
          curl -k --disable --disable-eprt -s https://tea-cup.midori-ai.xyz/download/helper_app.py > helper_app.py
          curl -k --disable --disable-eprt -s https://raw.githubusercontent.com/lunamidori5/Midori-AI-Subsystem-Manager/master/midori_ai_manager/huggingface_downloader.py > huggingface_downloader.py

      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install tor-proxy
          pip install -r ./Subsystem-Manager/model_installer/requirements.txt
          
      - name: Download Other Programs
        run: |
          python3 helper_app.py midori_ai_login_app.py
          
      - name: Download the Uploader
        run: |
          python3 helper_app.py git_uploader.py
      
      - name: Build Programs
        run: |
          pyinstaller --onefile --clean --distpath /tmp/artifacts/ helper_app.py
          pyinstaller --onefile --clean --distpath /tmp/artifacts/ midori_ai_login_app.py
          pyinstaller --onefile --clean --distpath /tmp/artifacts/ huggingface_downloader.py
      
      - name: Move Exec
        run: |
          mv /tmp/artifacts/helper_app midori_ai_downloader
          mv /tmp/artifacts/midori_ai_login_app midori_ai_login
          mv /tmp/artifacts/huggingface_downloader hf-downloader
      
      - name: Upload Programs
        run: |
          python3 git_uploader.py --type Linux --username "${{ secrets.MIDORI_AI_USERNAME }}" --password "${{ secrets.MIDORI_AI_PASSWORD }}" --twoflogin "${{ secrets.MIDORI_AI_TFA }}" --file "midori_ai_downloader" --filename "pixelarch-midori-ai-downloader"
          python3 git_uploader.py --type Linux --username "${{ secrets.MIDORI_AI_USERNAME }}" --password "${{ secrets.MIDORI_AI_PASSWORD }}" --twoflogin "${{ secrets.MIDORI_AI_TFA }}" --file "hf-downloader" --filename "pixelarch-hf-downloader"
          python3 git_uploader.py --type Linux --username "${{ secrets.MIDORI_AI_USERNAME }}" --password "${{ secrets.MIDORI_AI_PASSWORD }}" --twoflogin "${{ secrets.MIDORI_AI_TFA }}" --file "midori_ai_login" --filename "pixelarch-midori-ai-login"

  