name: Update PixelArch and Cluster OS

on:
  workflow_dispatch:
  schedule:
    - cron: '30 10 * * *'

jobs:

  push_arch_to_hub:
    name: Push Midori AI's PixelArch (Arch Linux) to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/pixelarch
          tags: |
            type=raw,value=latest
            type=raw,value=quartz

      - name: Build and push PixelArch Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Cluster-OS/pixelarch_os/
          file: ./Cluster-OS/pixelarch_os/arch_dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Clean up Docker Cache
        run: |
          docker image prune -f

  push_cluster_os_arch_to_hub:
    name: Push Midori AI's PixelArch (Cluster OS) to Docker Hub
    runs-on: ubuntu-latest
    needs: push_arch_to_hub
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/midori_ai_cluster
          tags: |
            type=raw,value=latest

      - name: Build and push Cluster OS (Arch Linux) Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Cluster-OS/aiclusteros/
          file: ./Cluster-OS/aiclusteros/dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Clean up Docker Cache
        run: |
          docker image prune -f

  push_pixelarch_ver_amethyst_to_hub:
    name: Push Midori AI's PixelArch (Amethyst) to Docker Hub
    runs-on: ubuntu-latest
    needs: push_arch_to_hub
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/pixelarch
          tags: |
            type=raw,value=amethyst

      - name: Build and push PixelArch OS (Amethyst) Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Cluster-OS/pixelarch_os/
          file: ./Cluster-OS/pixelarch_os/arch_dockerfile_amethyst
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_pixelarch_ver_topaz_to_hub:
    name: Push Midori AI's PixelArch (Topaz) to Docker Hub
    runs-on: ubuntu-latest
    needs: push_pixelarch_ver_amethyst_to_hub
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/pixelarch
          tags: |
            type=raw,value=topaz

      - name: Build and push PixelArch OS (Topaz) Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Cluster-OS/pixelarch_os/
          file: ./Cluster-OS/pixelarch_os/arch_dockerfile_topaz
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_pixelarch_ver_emerald_to_hub:
    name: Push Midori AI's PixelArch (Emerald) to Docker Hub
    runs-on: ubuntu-latest
    needs: push_pixelarch_ver_topaz_to_hub
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/pixelarch
          tags: |
            type=raw,value=emerald

      - name: Build and push PixelArch OS (Emerald) Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Cluster-OS/pixelarch_os/
          file: ./Cluster-OS/pixelarch_os/arch_dockerfile_emerald
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}