name: 'Build and Upload to Server'

on:
  workflow_dispatch:

jobs:
  Build-Subsystem-Manager:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Update Version Name
        run: |
          mkdir -p /tmp/artifacts
          cp ./other_files/midori_program_ver.txt /tmp/artifacts

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      
      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install -r ./other_files/model_installer/requirements.txt
      
      - name: Build
        run: |
          pyinstaller --onefile --distpath /tmp/artifacts/ --add-data ./other_files/midori_program_ver.txt:. ./other_files/model_installer/subsystem_manager.py

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: subsystem-manager-${{ matrix.os }}
          path: /tmp/artifacts/*
        
  Push-Build-To-Server:
    needs: [Build-Subsystem-Manager]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Fetch Artifacts
        uses: actions/download-artifact@v4

      - name: Install Dependencies
        run: |
          pip install requests

      - name: View Artifacts
        run: |
          ls

      - name: Upload Artifacts to Server
        run: |
          echo python3.10 uploadfile -f 